// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package dall_e_connector.proxies.constants;

import com.mendix.core.Core;

public class Constants
{
	/**
	 * @deprecated
	 * The default constructor of the Constants class should not be used.
	 * Use the static get methods instead.
	 */
	@java.lang.Deprecated(since = "9.12", forRemoval = true)
	public Constants() {}

	// These are the constants for the DALL_E_Connector module

	public static java.lang.String getCON_ApiKey()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("DALL_E_Connector.CON_ApiKey");
	}

	/**
	* Should be https://api.openai.com/v1/images/generations
	* 
	* Don't change unless you know what you are doing.
	*/
	public static java.lang.String getCON_Endpoint_URL()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("DALL_E_Connector.CON_Endpoint_URL");
	}
}